#!/usr/bin/env python3
"""Build the public reading site for the current week from a production database.

    python scripts/build_public_site.py --current --db data/nfl_props.db \
        --archive published-site --out public-site --label fresh

The production model cards are always published separately as model-cards.html.
A checksummed, same-week analyst dashboard keeps its presentation and original
quote clocks; automated data refreshes never overwrite it. Without that seed,
the generated homepage has native collapsed evidence and game-jump navigation.
Archived week reports and game pages are carried over from ``--archive``.
``results.html`` and ``api/results.json`` show the settled issued-pick ledger
(``nflvalue/issued_results.py``) with its own settlement clock. ``--label results``
(the results-only job) renders the week's cards at their own run clock, so a
settlement refresh never presents saved cards as a fresh forecast.
``publication.json`` records file hashes and separate model/analyst provenance.

Exit codes (fail closed; the previous publication stays live on any non-zero):
  0  built
  1  missing/corrupt input (no DB, no leans table, unreadable archive)
  3  nothing to publish: no leans stored for the target week
  4  refused: a lean for the target week lacks recorded provenance or was not
     produced by the football-only forecast
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import html
import json
import os
import re
import shutil
import sqlite3
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from nflvalue import issued_results as ir  # noqa: E402
from nflvalue import all_props as allprops  # noqa: E402
from nflvalue import pick_cards as pc  # noqa: E402

ARCHIVE_PATTERNS = [
    re.compile(r"reports/[0-9]{4}/week-(?:[1-9]|1[0-9]|2[0-2])\.html\Z"),
    re.compile(r"games/[0-9]{4}_[0-9]{2}_[A-Za-z]{2,3}_[A-Za-z]{2,3}\.html\Z"),
    re.compile(r"games/(?:pages|index)\.json\Z"),
    re.compile(r"(?:history|dashboard)\.html\Z"),
    re.compile(r"assets/(?:[^/]+/)*[^/]+\.(?:css|js|svg|png|ico)\Z"),
]
LABELS = {
    "fresh": "Generated by a scheduled production run from the quotes it captured.",
    "replay": ("REPLAY: the full production pipeline re-run on final code against quotes captured "
               "earlier (clocks below). Prices may have moved since capture."),
    "results": ("RESULTS UPDATE: only the settled results changed. The cards below are the saved output of "
                "the runs listed, rendered at their own run clock; they are not a new forecast."),
}
SETTLEMENT_LABELS = {"recommendations_given": "Given before kickoff",
                     "delivered_historical_import": ("Delivered recommendations imported after the game (historical: "
                                                     "original pregame issue clock kept; graded; not prospective "
                                                     "confirmation)"),
                     "retrospective": "Recorded after kickoff (retrospective; not a prospective record)",
                     "watch_published": "Watch list (not recommendations)",
                     "generated_not_shown": "Generated, publication not evidenced"}
CSS = ("body{font:15px system-ui;max-width:900px;margin:auto;padding:1em}"
       ".card{border:1px solid #ccc;border-radius:8px;padding:.8em;margin:.8em 0}"
       ".s{font-weight:700;text-transform:uppercase}.muted{color:#555;font-size:13px}"
       ".banner{background:#eef5ff;border:1px solid #9ab;padding:.7em;margin:.6em 0}"
       "nav a{margin-right:1em}"
       ".fe-panel{border-top:1px dashed #bbb;margin-top:.5em;padding-top:.4em;font-size:13px}"
       ".fe-head,.fe-cat{font-weight:600}.fe-panel ul{margin:.2em 0 .4em 1.1em;padding:0}"
       ".fe-d,.fe-s,.fe-c,.fe-m,.fe-r{color:#555}.fe-c{color:#8a4b00}"
       "*{box-sizing:border-box}body{line-height:1.5;color:#182233;overflow-wrap:anywhere}"
       "nav{display:flex;flex-wrap:wrap;gap:4px 10px}nav a{display:inline-flex;align-items:center;min-height:44px}"
       "a{color:#17529c}summary{cursor:pointer;min-height:44px;padding:10px;font-weight:600}"
       "details{border:1px solid #d5dce6;border-radius:8px;margin:8px 0}details[open]>summary{border-bottom:1px solid #d5dce6}"
       ".game-jumps a{border:1px solid #d5dce6;border-radius:8px;padding:4px 10px;text-decoration:none}"
       "section{scroll-margin-top:8px}.banner{padding:0}.banner .provenance{padding:10px}"
       "h1{font-size:24px}h2{font-size:19px}section .card{border:0;margin:0}"
       ".board-caveat{max-width:72ch}.picks-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:14px}"
       ".pick-card,.ap-game{border:1px solid #d5dce6;border-radius:10px;padding:16px;background:#fff}"
       ".pick-card h3,.ap-game h3{margin:.2em 0}.pick-game,.game-time,.pick-price,.no-pick{margin:.25em 0;color:#4a596d}"
       ".pick-price{font-weight:700;color:#182233}.pick-risk{border-left:3px solid #9b4d00;padding-left:10px}"
       ".game-jumps{margin:10px 0 16px}.game-jumps a{border-radius:999px}.ap-game{margin:10px 0}"
       ".research-download{margin:24px 0}@media(max-width:540px){.pick-card,.ap-game{padding:14px}.picks-grid{grid-template-columns:minmax(0,1fr)}}")


class Refused(Exception):
    def __init__(self, code, msg):
        super().__init__(msg)
        self.code = code


def current_week():
    sys.path.insert(0, os.path.join(ROOT, "scripts"))
    import auto_weekly
    return auto_weekly.current_week(auto_weekly.load_slate(), auto_weekly.now_et())


def collect(db_path, season, week, now):
    if not os.path.isfile(db_path):
        raise Refused(1, f"database not found: {db_path}")
    conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    try:
        cols = [r[1] for r in conn.execute("PRAGMA table_info(leans)")]
        if not cols:
            raise Refused(1, "leans table missing")
        n = conn.execute("SELECT COUNT(*) FROM leans WHERE season=? AND week=?", (season, week)).fetchone()[0]
        if n == 0:
            raise Refused(3, f"no leans stored for {season} week {week}")
        if "run_id" not in cols:
            raise Refused(4, "leans have no provenance columns (pre-migration-4 database)")
        bad = conn.execute(
            "SELECT COUNT(*) FROM leans WHERE season=? AND week=? AND (run_id IS NULL OR code_sha IS NULL "
            "OR forecast_version IS NULL OR forecast_version NOT LIKE ?)",
            (season, week, pc.FOOTBALL_ONLY_PREFIX + "%")).fetchone()[0]
        if bad:
            raise Refused(4, f"{bad} lean(s) for {season} week {week} lack football-only provenance")
        payload = pc.week_cards(conn, season, week, now=now)
        runs = [dict(zip(("run_id", "code_sha", "forecast_version", "ranker_sha256", "clock", "as_of",
                          "created_at"), r)) for r in conn.execute(
            "SELECT DISTINCT run_id, code_sha, forecast_version, ranker_sha256, clock, as_of, created_at "
            "FROM leans WHERE season=? AND week=? ORDER BY created_at", (season, week))]
        q = conn.execute("SELECT MIN(quote_ts), MAX(quote_ts), COUNT(quote_ts) FROM leans "
                         "WHERE season=? AND week=?", (season, week)).fetchone()
    except sqlite3.DatabaseError as exc:
        raise Refused(1, f"database unreadable: {exc}")
    finally:
        conn.close()
    payload["runs"] = runs
    from nflvalue import factor_integration as fimod
    conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    try:
        payload["factor_receipts"] = list(fimod.load_receipts(conn, season, week).values())
        on_board = {r["run_id"] for r in runs}
        ctx = [r for (run, _g), rs in fimod.load_context_records(conn, season, week).items()
               if run in on_board for r in rs]
    finally:
        conn.close()
    clocks = sorted(r["fetched_at"] for r in ctx if r.get("fetched_at"))
    payload["context_captured"] = (f"primary-source fetches up to {clocks[-1]}" if clocks else None)
    payload["quote_clocks"] = {"earliest": q[0], "latest": q[1], "leans_with_quote": q[2]}
    return payload


def page(title, body, nav=True, depth=0):
    e = html.escape
    prefix = '../' * depth
    links = (f'<nav><a href="{prefix}index.html">This week</a><a href="{prefix}best-bets.html">Watch list</a>'
             f'<a href="{prefix}all-props.html">All player props</a>'
             f'<a href="{prefix}model-cards.html">Model cards</a>'
             f'<a href="{prefix}reports/latest.html">Full report</a><a href="{prefix}results.html">Results</a>'
             f'<a href="{prefix}research.html">Research</a><a href="{prefix}coverage.html">Coverage</a>'
             f'<a href="{prefix}history.html">Archive</a></nav>'
             if nav else "")
    # Inline the committed UI bridge so scheduled rebuilds retain mobile
    # scrolling behavior at every report depth, even with an empty archive.
    with open(os.path.join(ROOT, "published-site", "assets", "hub-scroll.js"), encoding="utf-8") as f:
        scroll_bridge = f.read()
    return (f"<!doctype html><html><head><meta charset='utf-8'><title>{e(title)}</title>"
            '<meta name="viewport" content="width=device-width, initial-scale=1">'
            f"<style>{CSS}</style></head><body>{links}{body}"
            f"<script>{scroll_bridge}</script></body></html>")


NEW_FORECAST_HOURS = 3.0


def _clock(value):
    try:
        t = dt.datetime.fromisoformat(str(value).replace("Z", "+00:00")) if value else None
    except ValueError:
        return None
    return t if t is None or t.tzinfo else t.replace(tzinfo=dt.timezone.utc)


def clocks(payload, label, published_at, results_checked_at=None, research_checked_at=None):
    """Every clock a reader needs, kept apart: publishing a page is not a new forecast or price.

    ``new_forecast_in_this_publication`` is true only for a ``fresh`` build whose newest forecast
    run is at most NEW_FORECAST_HOURS older than the publish clock; a no-op/deploy/results
    rebuild of saved output says so instead of inheriting generic fresh copy."""
    runs = payload.get("runs") or []
    as_of = max((r["as_of"] for r in runs if r.get("as_of")), default=None)
    q = payload.get("quote_clocks") or {}
    pub, fc = _clock(published_at), _clock(as_of)
    age = round((pub - fc).total_seconds() / 3600, 1) if pub and fc else None
    new = label == "fresh" and age is not None and age <= NEW_FORECAST_HOURS
    missing = [m for m, bad in (("forecast run clock", fc is None), ("quote clock", not q.get("latest")),
                                ("settlement check", not results_checked_at),
                                ("research evidence loop", not research_checked_at)) if bad]
    return {"published_at": published_at, "forecast_as_of": as_of,
            "forecast_code_shas": sorted({r["code_sha"] for r in runs if r.get("code_sha")}),
            "forecast_versions": sorted({r["forecast_version"] for r in runs if r.get("forecast_version")}),
            "quote_clock_earliest": q.get("earliest"), "quote_clock_latest": q.get("latest"),
            "leans_with_quote": q.get("leans_with_quote"), "results_updated_at": results_checked_at,
            "research_checked_at": research_checked_at, "forecast_age_hours_at_publish": age,
            "new_forecast_in_this_publication": new, "missing": missing}


def clock_line(c):
    e = html.escape
    lead = ("New forecast run in this publication." if c["new_forecast_in_this_publication"] else
            "<b>NO NEW FORECAST OR PRICE IN THIS PUBLICATION</b>: it re-renders saved output.")
    gaps = f" Missing: {e(', '.join(c['missing']))}." if c["missing"] else ""
    return (f"<p class=clocks>{lead} Published {e(str(c['published_at']))}; newest forecast run "
            f"{e(str(c['forecast_as_of']))} (code {e(', '.join(x[:12] for x in c['forecast_code_shas']) or 'unknown')}); "
            f"quotes captured {e(str(c['quote_clock_earliest']))} to {e(str(c['quote_clock_latest']))}; "
            f"results checked {e(str(c['results_updated_at']))}.{gaps}</p>")


def header(payload, label, generated_at, clock_info=None):
    e = html.escape
    runs = "; ".join(f"{r['clock']} run {r['run_id']} (code {r['code_sha'][:12]}, {r['forecast_version']}, "
                     f"ranker {(r['ranker_sha256'] or 'none')[:12]}, as of {r['as_of']})" for r in payload["runs"])
    qc = payload["quote_clocks"]
    c = payload["counts"]
    ctx = payload.get("context_captured") or "no sourced context file for this week"
    return (f"<h1>{payload['season']} week {payload['week']}: evidence cards</h1>"
            f"<p><b>No card is a recommended wager.</b> Saved model output; quotes are not live.</p>"
            + (clock_line(clock_info) if clock_info else "") +
            f"<details class=banner><summary>Run timestamps, quote clocks and model caveats</summary><div class=provenance>"
            f"<b>{e(label.upper())}</b>. {e(LABELS[label])}<br>"
            f"Generated {e(generated_at)}. Quote clocks {e(str(qc['earliest']))} to {e(str(qc['latest']))}. "
            f"Runs: {e(runs)}.<br>Status counts: {c['actionable']} actionable, {c['watch']} watch, "
            f"{c['research']} research, {c['pass']} pass. <b>No card is a recommended wager.</b> "
            f"{e(pc.VALIDATION_NOTE)} Selection uses only the football forecast; prices are read "
            f"afterwards for breakeven/EV. No guaranteed outcomes.<br>"
            f"<b>Factor panels</b> show what the run that made each pick recorded: stages that changed the "
            f"projection (as executed), stages checked with no change, ordering-only inputs, a SHADOW "
            f"role/opportunity forecast (experimental learned weights; failed its bias gate; never changes "
            f"the pick), sourced context that is not a model input, and missing data (never treated as "
            f"healthy in this context layer; the primary pipeline's older availability step still treats a "
            f"player with no matched injury row as available). Context was captured by {e(ctx)}; each card "
            f"shows only the context recorded by the run that made it. The odds quote clocks above are "
            f"unchanged.</div></details>")


def grouped_cards(cards):
    """Readable, native-HTML navigation and disclosure; no JS dependency."""
    groups = {}
    for card in cards:
        groups.setdefault(str(card.get('game_id') or 'unknown'), []).append(card)
    e = html.escape
    links, sections = [], []
    for game, rows in groups.items():
        anchor = 'g-' + re.sub(r'[^A-Za-z0-9_-]', '-', game)
        label = ' @ '.join(game.split('_')[-2:])
        links.append(f'<a href="#{e(anchor)}">{e(label)}</a>')
        items = []
        for card in rows:
            quote = card.get('quote') or {}
            price = f"{quote.get('book', '')} {quote.get('price_american', '')}" if quote else 'no executable quote'
            summary = (f"{card['player']} · {card['market'].replace('_', ' ')} "
                       f"{card['side']} {card['line']} · {price} · {card['status']}")
            items.append(f'<details class="model-card"><summary>{e(summary)}</summary>'
                         + pc.render_cards_html([card]) + '</details>')
        sections.append(f'<section id="{e(anchor)}"><h2>{e(label)}</h2>' + ''.join(items) + '</section>')
    return '<nav class="game-jumps" aria-label="Jump to game">' + ''.join(links) + '</nav>' + ''.join(sections)


def analyst_reading(archive, season, week):
    """Keep reviewed same-week presentation separate from production model data."""
    if not archive or not os.path.isfile(os.path.join(archive, 'publication.json')):
        return None
    with open(os.path.join(archive, 'publication.json'), encoding='utf-8') as f:
        manifest = json.load(f)
    if (manifest.get('season'), manifest.get('week')) != (season, week) or not manifest.get('analyst_card'):
        return None
    names = ('index.html', 'best-bets.html', 'reports/latest.html', f'reports/{season}/week-{week}.html')
    documents = {}
    for name in names:
        path = os.path.join(archive, name)
        with open(path, 'rb') as f:
            data = f.read()
        if hashlib.sha256(data).hexdigest() != manifest.get('files', {}).get(name):
            raise Refused(1, f'analyst reading checksum mismatch: {name}')
        documents[name] = data.decode('utf-8')
    analyst = manifest['analyst_card']
    hub_path = os.path.join(archive, 'api', 'hub.json')
    if os.path.isfile(hub_path):
        with open(hub_path, encoding='utf-8') as f:
            analyst = json.load(f).get('analyst_card', analyst)
    provenance = manifest.get('reading_experience') or {
        'kind': 'preserved-analyst-snapshot',
        'quote_clocks': manifest.get('quote_clocks'),
        'source_as_of': manifest.get('source_as_of'),
        'runs': manifest.get('runs'),
    }
    return documents, analyst, provenance


def results_page(doc):
    """Settled issued picks, section by section; never pooled, losses and violations kept."""
    e = html.escape
    parts = [f"<h1>Issued-pick results</h1><p>Settlement checked {e(str(doc.get('results_checked_at')))}. "
             f"{e(doc['note'])}</p>"]
    for name, sec in doc["sections"].items():
        rows = sec["rows"]
        c = sec.get("counts") or {}
        parts.append(f"<h2>{e(SETTLEMENT_LABELS.get(name, name))}</h2>")
        if not rows:
            parts.append("<p>None settled.</p>")
            continue
        parts.append(f"<p>{c.get('win', 0)} won, {c.get('loss', 0)} lost, {c.get('push', 0)} pushed, "
                     f"{c.get('void', 0)} void, {c.get('unresolved', 0)} unresolved.</p>")
        if name == "generated_not_shown":
            continue
        items = []
        for r in rows:
            price = (f"{r['quote_book']} {r['quote_price']:.3f} (decimal)" if r.get("quote_book")
                     and r.get("quote_price") else "no recorded quote")
            fix = "".join(f" Earlier grade {e(str(x['settlement']))} at {e(str(x['actual']))} "
                          f"(box captured {e(str(x['actuals_captured_at']))})." for x in r["corrections"])
            items.append(
                f"<li><b>{e(str(r['settlement']).upper())}</b> {e(str(r.get('player_name') or ''))} "
                f"{e(str(r['market']))} {e(str(r['side']))} {e(str(r['line']))} &middot; {e(price)} &middot; "
                f"actual {e(str(r['actual']))} &middot; {e(str(r['game_id']))} &middot; tier {e(str(r['tier']))}, "
                f"policy {e(str(r['policy_class']))} <span class=muted>(decided {e(str(r['decision_ts']))}; "
                + (f"originally issued {e(str(r['original_issue_ts']))}, imported after the game; "
                   if r.get("historical_import") else "") +
                f"final box captured {e(str(r['actuals_captured_at']))}: {e(str(r['actuals_url']))}; "
                f"{e(str(r['detail']))}.{fix})</span></li>")
        parts.append("<ul>" + "".join(items) + "</ul>")
    parts.append(f"<p class=muted>{len(doc['pending'])} issued record(s) await a verified official final. "
                 "Book rules not verified here: " + e("; ".join(doc["book_rules_unverified"])) + "</p>")
    return page("Issued-pick results", "".join(parts))


def research_page(doc):
    """The research evidence loop's status: descriptive counts and exact missing-data gates."""
    e = html.escape
    parts = [f"<h1>Research status</h1><p>Evidence loop checked {e(str(doc.get('checked_at')))}. "
             f"{e((doc.get('promotion') or {}).get('statement') or doc.get('note') or '')}</p>"]
    pro = doc.get("prospective") or {}
    parts.append(f"<p>Prospective confirmation rows settled: {pro.get('settled_scored', 0)} "
                 f"({pro.get('unused_since_freeze', 0)} untouched since the registry freeze "
                 f"{e(str(doc.get('registry_frozen_at')))}; {pro.get('game_clusters', 0)} game clusters). "
                 f"Historical/postgame imports: {doc.get('historical_imports', 0)} (never confirmation).</p>")
    for name, sec in (doc.get("sections") or {}).items():
        o = sec.get("outcomes") or {}
        parts.append(f"<h2>{e(SETTLEMENT_LABELS.get(name, name))}</h2><p>{sec.get('n', 0)} record(s): "
                     f"{o.get('win', 0)} won, {o.get('loss', 0)} lost, {o.get('push', 0)} pushed, "
                     f"{o.get('void', 0)} void, {o.get('pending', 0)} pending. By policy class: "
                     + e("; ".join(f"{k} {v.get('win', 0)}-{v.get('loss', 0)}" for k, v in
                                   (sec.get("by_policy_class") or {}).items()) or "none") + "</p>")
    parts.append("<h2>Missing-data gates</h2><ul>" + "".join(f"<li>{e(g)}</li>" for g in
                                                             doc.get("missing_data_gates") or []) + "</ul>")
    parts.append("<h2>Candidates</h2><ul>" + "".join(f"<li>{e(c['candidate_id'])}: {e(c['status'])}</li>"
                                                     for c in doc.get("candidates") or []) + "</ul>")
    return page("Research status", "".join(parts))


def coverage_doc(payload):
    """Per-run player-prop and game-line coverage, kept as separate products.

    A game-line answer (moneyline, spread, total) cannot establish player-prop
    availability, and a prop board cannot establish a game line. Runs that
    predate either receipt say so rather than inheriting or fabricating coverage.
    """
    runs = []
    for rec in payload.get("factor_receipts") or []:
        rec = rec if isinstance(rec, dict) else {}
        extra = rec.get("extra") or {}
        props = rec.get("odds_coverage") or extra.get("odds_coverage")
        game_lines = rec.get("game_lines") or extra.get("game_lines")
        runs.append({
            "run_id": rec.get("run_id"), "clock": rec.get("clock"), "as_of": rec.get("as_of"),
            # v1 compatibility: these three aliases always mean player props.
            "recorded": bool(props), "summary": (props or {}).get("summary"),
            "games": (props or {}).get("games"),
            "props": {"recorded": bool(props), "summary": (props or {}).get("summary"),
                      "games": (props or {}).get("games")},
            "game_lines": {"recorded": bool(game_lines), "summary": (game_lines or {}).get("summary"),
                           "games": (game_lines or {}).get("games")},
        })
    return {"schema": "fablesfable.odds_coverage.v2", "season": payload.get("season"), "week": payload.get("week"),
            "note": ("Provider coverage as recorded by the issuing runs. Player props and game lines are "
                     "separate products; a missing quote is never shown as a synthetic price."), "runs": runs}


def _coverage_table(title, coverage, game_lines=False):
    e = html.escape
    if not coverage["recorded"]:
        return (f"<h3>{e(title)}</h3>"
                "<p>Coverage not recorded by this run (it predates this receipt).</p>")
    summary = e(json.dumps(coverage["summary"], sort_keys=True, default=str))
    rows = coverage["games"] or {}
    parts = [f"<h3>{e(title)}</h3><p class=muted>{summary}</p>"]
    if game_lines:
        parts.append("<table><thead><tr><th>Game</th><th>State</th><th>Capture clock</th>"
                     "<th>Book clocks</th><th>Age (h)</th><th>Books by market</th>"
                     "<th>Markets offered / missing</th><th>Books missing</th></tr></thead><tbody>")
        for gid, g in sorted(rows.items()):
            clocks = f"{g.get('book_clock_min')} to {g.get('book_clock_max')}"
            markets = f"{g.get('markets_offered')} / {g.get('markets_missing')}"
            parts.append(f"<tr><td>{e(str(gid))}</td><td>{e(str(g.get('state')))}</td>"
                         f"<td>{e(str(g.get('capture_clock')))}</td><td>{e(clocks)}</td>"
                         f"<td>{e(str(g.get('quote_age_hours')))}</td>"
                         f"<td>{e(json.dumps(g.get('books_by_market'), sort_keys=True, default=str))}</td>"
                         f"<td>{e(markets)}</td><td>{e(str(g.get('books_missing')))}</td></tr>")
    else:
        parts.append("<table><thead><tr><th>Game</th><th>State</th><th>Recorded detail</th></tr></thead><tbody>")
        for gid, g in sorted(rows.items()):
            parts.append(f"<tr><td>{e(str(gid))}</td><td>{e(str(g.get('state')))}</td>"
                         f"<td>{e(json.dumps(g, sort_keys=True, default=str))}</td></tr>")
    parts.append("</tbody></table>")
    return "".join(parts)


def coverage_page(doc):
    e = html.escape
    parts = [f"<h1>Odds coverage</h1><p>{e(doc['note'])}</p>"]
    if not doc["runs"]:
        parts.append("<p>No issuing run is recorded for this week.</p>")
    for r in doc["runs"]:
        parts.append(f"<h2>{e(str(r['clock']))} run {e(str(r['run_id']))} (as of {e(str(r['as_of']))})</h2>")
        parts.append(_coverage_table("Player-prop coverage", r["props"]))
        parts.append(_coverage_table("Game-line coverage (moneyline / spread / total)", r["game_lines"],
                                     game_lines=True))
    return page("Odds coverage", "".join(parts))


def research_empty(checked_at=None):
    return {"schema": "fablesfable.research_status.v1", "checked_at": checked_at,
            "note": "The research evidence loop has not run in this production state yet; nothing was promoted.",
            "missing_data_gates": ["no evidence ledger in this production state"], "candidates": [],
            "sections": {}, "prospective": {}}


def research_readonly(db_path):
    path = os.path.join(os.path.dirname(os.path.abspath(db_path)), "research_status.json")
    try:
        with open(path) as f:
            return json.load(f)
    except (OSError, ValueError):
        return research_empty()


def build(payload, label, archive, out, generated_at, published_at=None, results=None, research=None,
          all_props_payload=None):
    if os.path.exists(out):
        shutil.rmtree(out)
    os.makedirs(out)
    files = {}

    def put(name, text):
        path = os.path.join(out, *name.split("/"))
        os.makedirs(os.path.dirname(path), exist_ok=True)
        data = text.encode()
        with open(path, "wb") as f:
            f.write(data)
        files[name] = hashlib.sha256(data).hexdigest()

    season, week = payload["season"], payload["week"]
    results = results or ir.export_empty()
    research = research or research_empty()
    all_props_payload = all_props_payload or allprops.load(None, None)
    clock_info = clocks(payload, label, published_at or generated_at, results.get("results_checked_at"),
                        research.get("checked_at"))
    head = header(payload, label, generated_at, clock_info)
    cards = grouped_cards(payload["cards"])
    watch = [c for c in payload["cards"] if c["status"] in ("actionable", "watch")]
    # A complete, persisted manual all-props screen is the reader-facing Week 5
    # snapshot. Scheduled database rebuilds may refresh model-cards.html, but
    # must not demote or erase the reviewed full-slate board from the landing page.
    manual_board = all_props_payload.get("state") == "ready" and all_props_payload.get("counts", {}).get("games") >= 15
    landing = allprops.render_page(all_props_payload) if manual_board else head + (cards or "<p>No leans.</p>")
    put("index.html", page(f"{season} week {week} cards", landing))
    put("best-bets.html", page(f"{season} week {week} watch list", head + (
        grouped_cards(watch) if watch else
        "<p>No card is actionable, and none currently qualifies for the watch list.</p>")))
    report = page(f"{season} week {week} report", head + cards)
    put("reports/latest.html", page(f"{season} week {week} report", head + cards, depth=1))
    put(f"reports/{season}/week-{week}.html", page(f"{season} week {week} report", head + cards, depth=2))
    put("model-cards.html", report)

    reading = analyst_reading(archive, season, week)
    if reading:
        documents, analyst, reading_provenance = reading
        for name, document in documents.items():
            # Idempotent UI-only notice; do not relabel old analyst quotes as fresh.
            document = re.sub(r'<!-- model-refresh-link -->.*?<!-- /model-refresh-link -->',
                              '', document, flags=re.DOTALL)
            prefix = '../' * name.count('/')
            notice = ('<!-- model-refresh-link --><aside style="padding:10px 12px;'
                      'border:1px solid #d5dce6;border-radius:8px;margin:10px 0;font:14px/1.5 system-ui">'
                      '<b>Saved analyst card.</b> Original selections and quote clocks are unchanged; '
                      'these are not live prices or in-game picks. '
                      f'<a href="{prefix}model-cards.html">Latest automated model cards ↗</a>'
                      '</aside><!-- /model-refresh-link -->')
            document = document.replace('<body>', '<body>' + notice, 1)
            put(name, document)

    archived = []
    if archive:
        if not os.path.isdir(archive):
            raise Refused(1, f"archive not found: {archive}")
        for dirpath, _dirs, names in os.walk(archive):
            for n in names:
                rel = os.path.relpath(os.path.join(dirpath, n), archive).replace(os.sep, "/")
                if rel == f"reports/{season}/week-{week}.html" or rel in files:
                    continue
                if any(p.fullmatch(rel) for p in ARCHIVE_PATTERNS):
                    with open(os.path.join(archive, rel), "rb") as f:
                        data = f.read()
                    path = os.path.join(out, *rel.split("/"))
                    os.makedirs(os.path.dirname(path), exist_ok=True)
                    with open(path, "wb") as f:
                        f.write(data)
                    files[rel] = hashlib.sha256(data).hexdigest()
                    archived.append(rel)
    if "history.html" not in files:
        put("history.html", page("Archive", "<p>No archived weeks.</p>"))
    weeks = sorted({(int(m.group(1)), int(m.group(2))) for m in
                    (re.fullmatch(r"reports/([0-9]{4})/week-([0-9]+)\.html", n) for n in files) if m})
    put("reports/index.json", json.dumps({"latest": {"season": season, "week": week,
                                                     "path": "reports/latest.html"},
                                          "weeks": [{"season": s, "week": w,
                                                     "path": f"reports/{s}/week-{w}.html"}
                                                    for s, w in weeks]}, indent=2))
    hub = {k: payload[k] for k in ("season", "week", "generated_at", "counts", "validated_markets",
                                   "runs", "quote_clocks")}
    hub.update({"label": label, "label_text": LABELS[label], "cards": payload["cards"], "clocks": clock_info,
                "factor_receipts": payload.get("factor_receipts") or [],
                "context_captured": payload.get("context_captured")})
    if reading:
        hub['analyst_card'] = analyst
    put("api/hub.json", json.dumps(hub, indent=2, default=str))
    put("results.html", results_page(results))
    put("api/results.json", json.dumps(results, indent=2, sort_keys=True, default=str))
    put("research.html", research_page(research))
    put("all-props.html", page("All player props", allprops.render_page(all_props_payload)))
    coverage = coverage_doc(payload)
    put("coverage.html", coverage_page(coverage))
    put("api/coverage.json", json.dumps(coverage, indent=2, sort_keys=True, default=str))
    put("api/research.json", json.dumps(research, indent=2, sort_keys=True, default=str))
    put("api/all-props.json", json.dumps(all_props_payload, indent=2, sort_keys=True, default=str))
    put("README.txt", f"FablesFable {season} week {week} evidence cards ({label}).\n"
        "Generated by scripts/build_public_site.py; no API keys, databases or model binaries.\n"
        "No card is a recommended wager.\n")
    manifest = {
        "schema_version": 2, "kind": "saved-model-analysis", "generator": "scripts/build_public_site.py",
        "label": label, "season": season, "week": week, "published_at": published_at or generated_at,
        "results_checked_at": results.get("results_checked_at"), "clocks": clock_info,
        "source_as_of": payload["quote_clocks"]["latest"] or max((r["as_of"] or "") for r in payload["runs"]),
        "quote_clocks": payload["quote_clocks"], "runs": payload["runs"],
        "counts": payload["counts"], "approved_bets": 0, "model_candidates": len(payload["cards"]),
        "all_props": {"schema": all_props_payload["schema"], "state": all_props_payload["state"],
                      "counts": all_props_payload["counts"]},
        "archived_files": sorted(archived), "files": dict(sorted(files.items())),
    }
    if reading:
        manifest['analyst_card'] = reading[1]
        manifest['reading_experience'] = reading[2]
    with open(os.path.join(out, "publication.json"), "w") as f:
        json.dump(manifest, f, indent=2, default=str)
        f.write("\n")
    return manifest


def run_clock(db_path, season, week):
    """The latest issuing-run clock of the week's stored leans (cards are rendered as of it).

    ``created_at`` first, then ``as_of``. Exit 3 when neither is a readable clock: a results
    refresh then publishes nothing rather than guessing a clock (the live site stays as it is)."""
    if not os.path.isfile(db_path):
        raise Refused(1, f"database not found: {db_path}")
    conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    try:
        row = conn.execute("SELECT MAX(created_at), MAX(as_of) FROM leans WHERE season=? AND week=?",
                           (season, week)).fetchone()
    except sqlite3.DatabaseError as exc:
        raise Refused(1, f"database unreadable: {exc}")
    finally:
        conn.close()
    for value in (row or ()):
        try:
            t = dt.datetime.fromisoformat(str(value).replace("Z", "+00:00")) if value else None
        except ValueError:
            t = None
        if t is not None:
            return t if t.tzinfo else t.replace(tzinfo=dt.timezone.utc)
    raise Refused(3, f"no readable run clock for {season} week {week}: results site not built")


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--db", default=os.path.join(ROOT, "data", "nfl_props.db"))
    ap.add_argument("--season", type=int)
    ap.add_argument("--week", type=int)
    ap.add_argument("--current", action="store_true", help="target the schedule's current week")
    ap.add_argument("--archive", default=os.path.join(ROOT, "published-site"))
    ap.add_argument("--out", required=True)
    ap.add_argument("--label", choices=sorted(LABELS), required=True)
    ap.add_argument("--game-cards", help="separate researched game_cards.json contract payload")
    ap.add_argument("--market-rows", help="separate researched market_rows.json contract payload")
    ap.add_argument("--now", help="ISO clock for staleness checks (tests); default: wall clock")
    a = ap.parse_args(argv)
    now = (dt.datetime.fromisoformat(a.now.replace("Z", "+00:00")) if a.now
           else dt.datetime.now(dt.timezone.utc))
    try:
        if a.current:
            cw = current_week()
            if cw is None:
                raise Refused(3, "no current REG week")
            season, week = int(cw[0]), int(cw[1])
        elif a.season and a.week:
            season, week = a.season, a.week
        else:
            raise Refused(1, "give --current or --season/--week")
        cards_now = run_clock(a.db, season, week) if a.label == "results" else now
        payload = collect(a.db, season, week, cards_now)
        snapshot = os.path.join(ROOT, "data", "research_snapshots", f"{season}-week-{week}")
        if not a.game_cards and not a.market_rows and os.path.isfile(os.path.join(snapshot, "game_cards.json")) and os.path.isfile(os.path.join(snapshot, "market_rows.json")):
            a.game_cards = os.path.join(snapshot, "game_cards.json")
            a.market_rows = os.path.join(snapshot, "market_rows.json")
        expected = None
        if a.game_cards or a.market_rows:
            try:
                expected = {str(card["event_id"]) for card in json.load(open(a.game_cards, encoding="utf-8"))}
            except (OSError, ValueError, KeyError, TypeError) as exc:
                raise Refused(1, f"cannot read expected events from researched game cards: {exc}")
        all_props_payload = allprops.load(a.game_cards, a.market_rows, expected_event_ids=expected)
        m = build(payload, a.label, a.archive, a.out, cards_now.isoformat(timespec="seconds"),
                  published_at=now.isoformat(timespec="seconds"), results=ir.export_readonly(a.db),
                  research=research_readonly(a.db), all_props_payload=all_props_payload)
    except Refused as exc:
        print(f"[site] not built (exit {exc.code}): {exc}")
        return exc.code
    print(f"[site] built {season} week {week} -> {a.out}: {len(m['files'])} files, counts {m['counts']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
