#!/usr/bin/env python3
"""Build the public reading site for the current week from a production database.

    python scripts/build_public_site.py --current --db data/nfl_props.db \
        --archive published-site --out public-site --label fresh

The top-level pages (index, best-bets, api/hub.json, reports/latest) become
this week's evidence cards; archived week reports and game pages are carried
over from ``--archive`` unchanged. ``publication.json`` records every file hash
plus the run/code/model/version provenance and the quote and run clocks.

Exit codes (fail closed; the previous publication stays live on any non-zero):
  0  built
  1  missing/corrupt input (no DB, no leans table, unreadable archive)
  3  nothing to publish: no leans stored for the target week
  4  refused: a lean for the target week lacks recorded provenance or was not
     produced by the football-only forecast
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import html
import json
import os
import re
import shutil
import sqlite3
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from nflvalue import pick_cards as pc  # noqa: E402

ARCHIVE_PATTERNS = [
    re.compile(r"reports/[0-9]{4}/week-(?:[1-9]|1[0-9]|2[0-2])\.html\Z"),
    re.compile(r"games/[0-9]{4}_[0-9]{2}_[A-Za-z]{2,3}_[A-Za-z]{2,3}\.html\Z"),
    re.compile(r"games/(?:pages|index)\.json\Z"),
    re.compile(r"(?:history|dashboard)\.html\Z"),
    re.compile(r"assets/(?:[^/]+/)*[^/]+\.(?:css|js|svg|png|ico)\Z"),
]
LABELS = {
    "fresh": "Generated by a scheduled production run from the quotes it captured.",
    "replay": ("REPLAY: the full production pipeline re-run on final code against quotes captured "
               "earlier (clocks below). Prices may have moved since capture."),
}
CSS = ("body{font:15px system-ui;max-width:900px;margin:auto;padding:1em}"
       ".card{border:1px solid #ccc;border-radius:8px;padding:.8em;margin:.8em 0}"
       ".s{font-weight:700;text-transform:uppercase}.muted{color:#555;font-size:13px}"
       ".banner{background:#eef5ff;border:1px solid #9ab;padding:.7em;margin:.6em 0}"
       "nav a{margin-right:1em}"
       ".fe-panel{border-top:1px dashed #bbb;margin-top:.5em;padding-top:.4em;font-size:13px}"
       ".fe-head,.fe-cat{font-weight:600}.fe-panel ul{margin:.2em 0 .4em 1.1em;padding:0}"
       ".fe-d,.fe-s,.fe-c,.fe-m,.fe-r{color:#555}.fe-c{color:#8a4b00}")


class Refused(Exception):
    def __init__(self, code, msg):
        super().__init__(msg)
        self.code = code


def current_week():
    sys.path.insert(0, os.path.join(ROOT, "scripts"))
    import auto_weekly
    return auto_weekly.current_week(auto_weekly.load_slate(), auto_weekly.now_et())


def collect(db_path, season, week, now):
    if not os.path.isfile(db_path):
        raise Refused(1, f"database not found: {db_path}")
    conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    try:
        cols = [r[1] for r in conn.execute("PRAGMA table_info(leans)")]
        if not cols:
            raise Refused(1, "leans table missing")
        n = conn.execute("SELECT COUNT(*) FROM leans WHERE season=? AND week=?", (season, week)).fetchone()[0]
        if n == 0:
            raise Refused(3, f"no leans stored for {season} week {week}")
        if "run_id" not in cols:
            raise Refused(4, "leans have no provenance columns (pre-migration-4 database)")
        bad = conn.execute(
            "SELECT COUNT(*) FROM leans WHERE season=? AND week=? AND (run_id IS NULL OR code_sha IS NULL "
            "OR forecast_version IS NULL OR forecast_version NOT LIKE ?)",
            (season, week, pc.FOOTBALL_ONLY_PREFIX + "%")).fetchone()[0]
        if bad:
            raise Refused(4, f"{bad} lean(s) for {season} week {week} lack football-only provenance")
        payload = pc.week_cards(conn, season, week, now=now)
        runs = [dict(zip(("run_id", "code_sha", "forecast_version", "ranker_sha256", "clock", "as_of",
                          "created_at"), r)) for r in conn.execute(
            "SELECT DISTINCT run_id, code_sha, forecast_version, ranker_sha256, clock, as_of, created_at "
            "FROM leans WHERE season=? AND week=? ORDER BY created_at", (season, week))]
        q = conn.execute("SELECT MIN(quote_ts), MAX(quote_ts), COUNT(quote_ts) FROM leans "
                         "WHERE season=? AND week=?", (season, week)).fetchone()
    except sqlite3.DatabaseError as exc:
        raise Refused(1, f"database unreadable: {exc}")
    finally:
        conn.close()
    payload["runs"] = runs
    from nflvalue import factor_integration as fimod
    conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    try:
        payload["factor_receipts"] = list(fimod.load_receipts(conn, season, week).values())
        on_board = {r["run_id"] for r in runs}
        ctx = [r for (run, _g), rs in fimod.load_context_records(conn, season, week).items()
               if run in on_board for r in rs]
    finally:
        conn.close()
    clocks = sorted(r["fetched_at"] for r in ctx if r.get("fetched_at"))
    payload["context_captured"] = (f"primary-source fetches up to {clocks[-1]}" if clocks else None)
    payload["quote_clocks"] = {"earliest": q[0], "latest": q[1], "leans_with_quote": q[2]}
    return payload


def page(title, body, nav=True):
    e = html.escape
    links = ('<nav><a href="index.html">This week</a><a href="best-bets.html">Watch list</a>'
             '<a href="reports/latest.html">Full report</a><a href="history.html">Archive</a></nav>'
             if nav else "")
    return (f"<!doctype html><html><head><meta charset='utf-8'><title>{e(title)}</title>"
            f"<style>{CSS}</style></head><body>{links}{body}</body></html>")


def header(payload, label, generated_at):
    e = html.escape
    runs = "; ".join(f"{r['clock']} run {r['run_id']} (code {r['code_sha'][:12]}, {r['forecast_version']}, "
                     f"ranker {(r['ranker_sha256'] or 'none')[:12]}, as of {r['as_of']})" for r in payload["runs"])
    qc = payload["quote_clocks"]
    c = payload["counts"]
    ctx = payload.get("context_captured") or "no sourced context file for this week"
    return (f"<h1>{payload['season']} week {payload['week']}: evidence cards</h1>"
            f"<div class=banner><b>{e(label.upper())}</b>. {e(LABELS[label])}<br>"
            f"Generated {e(generated_at)}. Quote clocks {e(str(qc['earliest']))} to {e(str(qc['latest']))}. "
            f"Runs: {e(runs)}.<br>Status counts: {c['actionable']} actionable, {c['watch']} watch, "
            f"{c['research']} research, {c['pass']} pass. <b>No card is a recommended wager.</b> "
            f"{e(pc.VALIDATION_NOTE)} Selection uses only the football forecast; prices are read "
            f"afterwards for breakeven/EV. No guaranteed outcomes.<br>"
            f"<b>Factor panels</b> show what the run that made each pick recorded: stages that changed the "
            f"projection (as executed), stages checked with no change, ordering-only inputs, a SHADOW "
            f"role/opportunity forecast (experimental learned weights; failed its bias gate; never changes "
            f"the pick), sourced context that is not a model input, and missing data (never treated as "
            f"healthy in this context layer; the primary pipeline's older availability step still treats a "
            f"player with no matched injury row as available). Context was captured by {e(ctx)}; each card "
            f"shows only the context recorded by the run that made it. The odds quote clocks above are "
            f"unchanged.</div>")


def build(payload, label, archive, out, generated_at):
    if os.path.exists(out):
        shutil.rmtree(out)
    os.makedirs(out)
    files = {}

    def put(name, text):
        path = os.path.join(out, *name.split("/"))
        os.makedirs(os.path.dirname(path), exist_ok=True)
        data = text.encode()
        with open(path, "wb") as f:
            f.write(data)
        files[name] = hashlib.sha256(data).hexdigest()

    season, week = payload["season"], payload["week"]
    head = header(payload, label, generated_at)
    cards = pc.render_cards_html(payload["cards"])
    watch = [c for c in payload["cards"] if c["status"] in ("actionable", "watch")]
    put("index.html", page(f"{season} week {week} cards", head + (cards or "<p>No leans.</p>")))
    put("best-bets.html", page(f"{season} week {week} watch list", head + (
        pc.render_cards_html(watch) if watch else
        "<p>No card is actionable, and none currently qualifies for the watch list.</p>")))
    report = page(f"{season} week {week} report", head + cards)
    put("reports/latest.html", report)
    put(f"reports/{season}/week-{week}.html", report)

    archived = []
    if archive:
        if not os.path.isdir(archive):
            raise Refused(1, f"archive not found: {archive}")
        for dirpath, _dirs, names in os.walk(archive):
            for n in names:
                rel = os.path.relpath(os.path.join(dirpath, n), archive).replace(os.sep, "/")
                if rel == f"reports/{season}/week-{week}.html" or rel in files:
                    continue
                if any(p.fullmatch(rel) for p in ARCHIVE_PATTERNS):
                    with open(os.path.join(archive, rel), "rb") as f:
                        data = f.read()
                    path = os.path.join(out, *rel.split("/"))
                    os.makedirs(os.path.dirname(path), exist_ok=True)
                    with open(path, "wb") as f:
                        f.write(data)
                    files[rel] = hashlib.sha256(data).hexdigest()
                    archived.append(rel)
    if "history.html" not in files:
        put("history.html", page("Archive", "<p>No archived weeks.</p>"))
    weeks = sorted({(int(m.group(1)), int(m.group(2))) for m in
                    (re.fullmatch(r"reports/([0-9]{4})/week-([0-9]+)\.html", n) for n in files) if m})
    put("reports/index.json", json.dumps({"latest": {"season": season, "week": week,
                                                     "path": "reports/latest.html"},
                                          "weeks": [{"season": s, "week": w,
                                                     "path": f"reports/{s}/week-{w}.html"}
                                                    for s, w in weeks]}, indent=2))
    hub = {k: payload[k] for k in ("season", "week", "generated_at", "counts", "validated_markets",
                                   "runs", "quote_clocks")}
    hub.update({"label": label, "label_text": LABELS[label], "cards": payload["cards"],
                "factor_receipts": payload.get("factor_receipts") or [],
                "context_captured": payload.get("context_captured")})
    put("api/hub.json", json.dumps(hub, indent=2, default=str))
    put("README.txt", f"FablesFable {season} week {week} evidence cards ({label}).\n"
        "Generated by scripts/build_public_site.py; no API keys, databases or model binaries.\n"
        "No card is a recommended wager.\n")
    manifest = {
        "schema_version": 2, "kind": "saved-model-analysis", "generator": "scripts/build_public_site.py",
        "label": label, "season": season, "week": week, "published_at": generated_at,
        "source_as_of": payload["quote_clocks"]["latest"] or max((r["as_of"] or "") for r in payload["runs"]),
        "quote_clocks": payload["quote_clocks"], "runs": payload["runs"],
        "counts": payload["counts"], "approved_bets": 0, "model_candidates": len(payload["cards"]),
        "archived_files": sorted(archived), "files": dict(sorted(files.items())),
    }
    with open(os.path.join(out, "publication.json"), "w") as f:
        json.dump(manifest, f, indent=2, default=str)
        f.write("\n")
    return manifest


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--db", default=os.path.join(ROOT, "data", "nfl_props.db"))
    ap.add_argument("--season", type=int)
    ap.add_argument("--week", type=int)
    ap.add_argument("--current", action="store_true", help="target the schedule's current week")
    ap.add_argument("--archive", default=os.path.join(ROOT, "published-site"))
    ap.add_argument("--out", required=True)
    ap.add_argument("--label", choices=sorted(LABELS), required=True)
    ap.add_argument("--now", help="ISO clock for staleness checks (tests); default: wall clock")
    a = ap.parse_args(argv)
    now = (dt.datetime.fromisoformat(a.now.replace("Z", "+00:00")) if a.now
           else dt.datetime.now(dt.timezone.utc))
    try:
        if a.current:
            cw = current_week()
            if cw is None:
                raise Refused(3, "no current REG week")
            season, week = int(cw[0]), int(cw[1])
        elif a.season and a.week:
            season, week = a.season, a.week
        else:
            raise Refused(1, "give --current or --season/--week")
        payload = collect(a.db, season, week, now)
        m = build(payload, a.label, a.archive, a.out, now.isoformat(timespec="seconds"))
    except Refused as exc:
        print(f"[site] not built (exit {exc.code}): {exc}")
        return exc.code
    print(f"[site] built {season} week {week} -> {a.out}: {len(m['files'])} files, counts {m['counts']}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
