"""Immutable ledger of pick cards, and of what happened to each: generated, published, delivered.

The user grades the picks the assistant GIVES; recording them is our bookkeeping.
A record is the card content itself (the exact HTML ``pick_cards.render_cards_html``
emits for it, plus the card JSON) with the issuing run's provenance, the quote
identity and the decision clock, as persisted by that run. What happened to the
record is a separate append-only EVENT:

* ``generated`` -- a run rendered the card (``pick_cards.write_week_cards``).
  Proof the system produced it, NOT proof anyone saw it.
* ``published`` -- the LIVE site served the card. Recorded only with a pages
  readback receipt (``scripts/publication_receipt.py``, run by website.yml after
  deployment) whose sha256s match the saved page; the event clock is the
  readback clock. A generated or uploaded artifact is never ``published``.
* ``delivered`` -- the assistant gave the pick to the user. There is NO automatic
  chat capture: it is recorded explicitly (``record_delivered`` /
  ``scripts/record_issued_pick.py delivered``) with the exact text and the
  source message id, at issuance.

Rules:

* Append-only. ``issued_picks`` and ``issued_pick_events`` rows are never updated
  or deleted (db migration 7 triggers abort both). A changed card is a NEW record
  with ``revision + 1`` naming the record it supersedes; the earlier record stays.
  Identical content is one record (id = sha256 of the content, surface-free), so
  the same card generated by a run and shown on the site is one record with two
  events.
* A later record for the same pick (a stale re-render that turned it to ``pass``,
  a line change) never erases an earlier one: graders keep every issued decision.
* Nothing is reconstructed after the fact. ``dist`` is written only when the
  recorder runs the issuing commit; otherwise NULL (interval metrics unavailable).
* ``pick_class``: ``recommendation`` (actionable card or an explicitly delivered
  pick), ``watch`` (watch list: not a recommendation), ``not_a_pick``
  (research/pass). ``tier`` keeps primary, experimental and analyst_override apart.
* Recording an archived page after kickoff is allowed (evidence of what was shown)
  but the event's ``recorded_at`` is the ledger clock, so graders treat it as
  retrospective, never as a prospective pick.
"""

from __future__ import annotations

import datetime as dt
import hashlib
import json
from typing import Dict, Iterable, List, Optional

TIERS = ("primary", "experimental", "analyst_override")
STAGES = ("generated", "published", "delivered")
PICK_CLASS = {"actionable": "recommendation", "watch": "watch", "research": "not_a_pick", "pass": "not_a_pick"}
ISSUED_CLASSES = ("recommendation", "watch")
# fields of the card that depend on the rendering clock, not on the decision
_VOLATILE = ("quote_age_hours",)
COLUMNS = ("record_id", "pick_key", "revision", "supersedes", "season", "week", "game_id", "player_id",
           "player_name", "market", "side", "line", "tier", "surface", "card_status", "pick_class",
           "run_id", "code_sha", "forecast_version", "ranker_sha256", "selection_source", "clock",
           "decision_ts", "quote_book", "quote_price", "quote_ts", "model_p_side", "mean", "sd", "dist",
           "display_html", "card_json", "recorded_at")
EVENT_COLUMNS = ("event_id", "record_id", "stage", "surface", "event_ts", "evidence_json", "recorded_at")


def _canon(obj) -> str:
    return json.dumps(obj, sort_keys=True, separators=(",", ":"), default=str)


def _sha(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()


def _now() -> str:
    return dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def pick_key(season: int, week: int, card: Dict, tier: str) -> str:
    return _sha(_canon([int(season), int(week), card.get("game_id"), card.get("player_id"),
                        card.get("market"), tier]))


def _recorded(value) -> Optional[str]:
    return None if value is None or str(value).startswith("unknown") else str(value)


def build_record(card: Dict, season: int, week: int, tier: str = "primary", surface: str = "run_reports",
                 display_html: Optional[str] = None, dist: Optional[str] = None,
                 pick_class: Optional[str] = None) -> Dict:
    """The content of one ledger record (no revision/chain/recorded_at yet)."""
    if tier not in TIERS:
        raise ValueError(f"unknown tier {tier!r}; choices: {TIERS}")
    if display_html is None:
        from .pick_cards import render_cards_html
        display_html = render_cards_html([card])
    stable = {k: v for k, v in card.items() if k not in _VOLATILE}
    prov = card.get("provenance") or {}
    q = card.get("quote") or {}
    return {
        "season": int(season), "week": int(week), "game_id": card.get("game_id"),
        "player_id": card.get("player_id"), "player_name": card.get("player"),
        "market": card.get("market"), "side": card.get("side"), "line": card.get("line"),
        "tier": tier, "surface": surface, "card_status": card.get("status"),
        "pick_class": pick_class or PICK_CLASS.get(card.get("status"), "not_a_pick"),
        "run_id": _recorded(prov.get("run_id")), "code_sha": _recorded(prov.get("code_sha")),
        "forecast_version": _recorded(prov.get("forecast_version")),
        "ranker_sha256": prov.get("ranker_sha256"), "selection_source": _recorded(prov.get("selection_source")),
        "clock": card.get("clock"), "decision_ts": card.get("run_as_of"),
        "quote_book": q.get("book"), "quote_price": q.get("price_decimal"), "quote_ts": q.get("captured_at"),
        "model_p_side": card.get("model_p_side"), "mean": card.get("mean"), "sd": card.get("sd"),
        "dist": dist, "display_html": display_html, "card_json": _canon(stable),
    }


# The id covers what was displayed and decided. Surface and dist are excluded so the same
# card published on the site is the record the run generated (dist depends on the recorder).
_NOT_CONTENT = ("record_id", "revision", "supersedes", "recorded_at", "surface", "dist")


def _content_id(rec: Dict) -> str:
    return _sha(_canon({k: rec.get(k) for k in COLUMNS if k not in _NOT_CONTENT}))


def _append(conn, rec: Dict, season: int, week: int, card: Dict, tier: str, recorded_at: str) -> bool:
    rec["record_id"] = _content_id(rec)
    rec["pick_key"] = pick_key(season, week, card, tier)
    if conn.execute("SELECT 1 FROM issued_picks WHERE record_id=?", (rec["record_id"],)).fetchone():
        return False
    prev = conn.execute("SELECT record_id, revision FROM issued_picks WHERE pick_key=? "
                        "ORDER BY revision DESC LIMIT 1", (rec["pick_key"],)).fetchone()
    rec["supersedes"], rec["revision"] = (prev[0], prev[1] + 1) if prev else (None, 1)
    rec["recorded_at"] = recorded_at
    conn.execute(f"INSERT INTO issued_picks ({','.join(COLUMNS)}) VALUES ({','.join('?' * len(COLUMNS))})",
                 [rec[c] for c in COLUMNS])
    return True


def _event(conn, record_id: str, stage: str, surface: str, event_ts: Optional[str], evidence: Dict,
           recorded_at: str) -> bool:
    """One stage event; the first sighting of (record, stage, surface, evidence) is kept."""
    if stage not in STAGES:
        raise ValueError(f"unknown stage {stage!r}; choices: {STAGES}")
    ev = {"record_id": record_id, "stage": stage, "surface": surface, "event_ts": event_ts,
          "evidence_json": _canon(evidence), "recorded_at": recorded_at}
    ev["event_id"] = _sha(_canon([record_id, stage, surface, event_ts, ev["evidence_json"]]))
    cur = conn.execute(f"INSERT OR IGNORE INTO issued_pick_events ({','.join(EVENT_COLUMNS)}) "
                       f"VALUES ({','.join('?' * len(EVENT_COLUMNS))})", [ev[c] for c in EVENT_COLUMNS])
    return cur.rowcount == 1


def _dist_for(card: Dict) -> Optional[str]:
    """The market's distribution family, only when this process runs the issuing commit."""
    from .projection import MARKETS
    from .provenance import run_provenance
    code = (card.get("provenance") or {}).get("code_sha")
    if not code or code != run_provenance().get("code_sha"):
        return None
    return (MARKETS.get(card.get("market")) or {}).get("dist")


def record_cards(conn, season: int, week: int, cards: Iterable[Dict], tier: str = "primary",
                 surface: str = "run_reports", recorded_at: Optional[str] = None) -> List[Dict]:
    """Stage ``generated``: append every card whose content is new; return the records written."""
    recorded_at = recorded_at or _now()
    written = []
    for card in cards:
        rec = build_record(card, season, week, tier=tier, surface=surface, dist=_dist_for(card))
        if _append(conn, rec, season, week, card, tier, recorded_at):
            written.append(rec)
        _event(conn, rec["record_id"], "generated", surface, card.get("run_as_of"),
               {"run_id": rec["run_id"]}, recorded_at)
    conn.commit()
    return written


def verify_publication(hub_path: str, manifest_path: str) -> Dict:
    """The saved page payload and its manifest, verified against each other.

    Raises unless the manifest lists ``api/hub.json`` with the payload's sha256 and names the
    same season/week/label. ``published_at`` is the manifest's own clock (self-reported)."""
    raw = open(hub_path, "rb").read()
    mraw = open(manifest_path, "rb").read()
    hub, man = json.loads(raw), json.loads(mraw)
    sha = hashlib.sha256(raw).hexdigest()
    if (man.get("files") or {}).get("api/hub.json") != sha:
        raise ValueError("hub.json sha256 is not the one its publication manifest lists")
    for k in ("season", "week", "label"):
        if hub.get(k) != man.get(k):
            raise ValueError(f"hub.json and manifest disagree on {k}")
    if not man.get("published_at"):
        raise ValueError("publication manifest has no published_at")
    return {"hub": hub, "evidence": {"hub_sha256": sha, "manifest_sha256": hashlib.sha256(mraw).hexdigest(),
                                     "label": man["label"], "published_at": man["published_at"],
                                     "clock_basis": "publication manifest published_at (self-reported)"}}


def publication_records(hub_path: str, manifest_path: str) -> List[Dict]:
    """In-memory records + ``published`` events for a verified saved page (no DB write).

    ``recorded_at`` is None: a record rebuilt at grading time is evidence of what the page
    showed, never of a prospective issue time."""
    pub = verify_publication(hub_path, manifest_path)
    hub, ev = pub["hub"], pub["evidence"]
    out = []
    for card in hub["cards"]:
        rec = build_record(card, hub["season"], hub["week"], tier="primary", surface=f"public_site:{ev['label']}")
        rec["record_id"] = _content_id(rec)
        rec["pick_key"] = pick_key(hub["season"], hub["week"], card, "primary")
        rec.update(revision=None, supersedes=None, recorded_at=None,
                   events=[{"record_id": rec["record_id"], "stage": "published", "surface": rec["surface"],
                            "event_ts": ev["published_at"], "evidence_json": _canon(ev), "recorded_at": None}])
        out.append(rec)
    return out


def record_publication(conn, hub_path: str, manifest_path: str, attestation: Dict,
                       recorded_at: Optional[str] = None) -> int:
    """Stage ``published`` for every card on a page the LIVE site was verified to serve.

    ``attestation`` is a pages readback receipt (``scripts/publication_receipt.py``): its
    hub/manifest sha256 must equal this saved page's, and its ``verified_at`` (when the live
    site served these bytes) is the event clock. Without it nothing is recorded -- building
    or uploading a page is not publishing it. ``recorded_at`` is the ledger clock (now): a
    receipt recorded after kickoff is retrospective evidence, never a prospective pick."""
    pub = verify_publication(hub_path, manifest_path)
    hub, ev = pub["hub"], pub["evidence"]
    att = attestation or {}
    if att.get("kind") != "pages_readback" or not att.get("run_id") or not att.get("page_url"):
        raise ValueError("no pages readback attestation: publication not recorded")
    if (att.get("hub_sha256"), att.get("manifest_sha256")) != (ev["hub_sha256"], ev["manifest_sha256"]):
        raise ValueError("readback attestation is for different bytes than this page")
    verified = att.get("verified_at")
    try:
        ok = dt.datetime.fromisoformat(str(verified).replace("Z", "+00:00")).tzinfo is not None
    except ValueError:
        ok = False
    if not ok:
        raise ValueError("readback attestation has no zoned verified_at clock")
    ev = {**ev, "clock_basis": "live pages readback verified_at", "deploy_run_id": att["run_id"],
          "page_url": att["page_url"], "readback_attempts": att.get("attempts")}
    recorded_at = recorded_at or _now()
    n = 0
    for card in hub["cards"]:
        rec = build_record(card, hub["season"], hub["week"], tier="primary",
                           surface=f"public_site:{ev['label']}")
        _append(conn, rec, hub["season"], hub["week"], card, "primary", recorded_at)
        n += _event(conn, rec["record_id"], "published", rec["surface"], verified, ev, recorded_at)
    conn.commit()
    return n


def record_delivered(conn, season: int, week: int, card: Dict, display_text: str, message_id: str,
                     delivered_at: str, channel: str, pick_class: str = "recommendation",
                     tier: str = "analyst_override", recorded_at: Optional[str] = None) -> Dict:
    """Stage ``delivered``: the exact text the user was given, its source message id and clock.

    ``card`` carries the quote identity and decision clock the pick was given at; nothing is
    filled in from later data. Call at issuance -- there is no automatic chat capture."""
    if not display_text or not display_text.strip():
        raise ValueError("a delivered pick needs the exact text given to the user")
    if not message_id or not str(message_id).strip():
        raise ValueError("a delivered pick needs the source message id")
    if not delivered_at or not channel:
        raise ValueError("a delivered pick needs its delivery clock and channel")
    if pick_class not in ISSUED_CLASSES:
        raise ValueError(f"pick_class must be one of {ISSUED_CLASSES}")
    recorded_at = recorded_at or _now()
    rec = build_record(card, season, week, tier=tier, surface=f"delivered:{channel}",
                       display_html=display_text, pick_class=pick_class)
    _append(conn, rec, season, week, card, tier, recorded_at)
    _event(conn, rec["record_id"], "delivered", f"delivered:{channel}", delivered_at,
           {"message_id": str(message_id), "channel": channel}, recorded_at)
    conn.commit()
    return rec


def load(conn, season: Optional[int] = None, week: Optional[int] = None) -> List[Dict]:
    """Records with their ``events`` (sorted), for grading and export."""
    sql, args = "SELECT * FROM issued_picks", []
    if season is not None:
        sql += " WHERE season=?" + (" AND week=?" if week is not None else "")
        args = [season] + ([week] if week is not None else [])
    cur = conn.execute(sql + " ORDER BY season, week, pick_key, revision", args)
    names = [d[0] for d in cur.description]
    recs = [dict(zip(names, r)) for r in cur.fetchall()]
    for r in recs:
        cur = conn.execute("SELECT * FROM issued_pick_events WHERE record_id=? "
                           "ORDER BY recorded_at, stage, event_id", (r["record_id"],))
        en = [d[0] for d in cur.description]
        r["events"] = [dict(zip(en, e)) for e in cur.fetchall()]
    return recs


def export(records: List[Dict]) -> str:
    """Deterministic JSON export (sorted, stable separators) of ledger records + events."""
    rows = sorted(records, key=lambda r: (r["season"], r["week"], r["pick_key"], r["revision"] or 0))
    return json.dumps({"schema": "fablesfable.issued_picks.v2", "records": rows},
                      sort_keys=True, indent=1, default=str) + "\n"
